quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=snailOpsUser
quarkus.datasource.password=snailOps
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/snail_ops

#quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.schema-management.strategy=update

quarkus.hibernate-orm.log.sql=true

quarkus.oidc.auth-server-url=http://localhost:8081/realms/snail-ops
quarkus.oidc.client-id=snail-ops-api

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger